---
kind: pipeline
type: docker
name: test multicast in drone

platform:
  os: linux
  arch: amd64

steps:
  - name: multicast-recv
    image: python:3.10.4
    commands: 
      - python -u ./recv.py

services: 
  - name: multicast-send
    image: python:3.10.4
    commands: 
      - sleep 5
      - python -u ./send.py
      - sleep 5

trigger:
  branch:
  - multicast-test
  event:
  - push
